### ISSUE TITLE
material-color-utilities

### ISSUE THREAD

**Issue by BlueBazze** [yetaanother/react-native-material-you#34]
The project files for `material-color-utilities` have been ignored in git.
Tried getting the files from the official repo.
The methods `intFromHex` & `hexFromInt`. I cant find them anywhere neither in a fork from the official or the official one.
Im guessing these are made by you.

If these two methods are custom by you.
Can i suggest they were put in this repo under something like `utils/colors`.
Also, the official repo isnt on npmjs. But the repo can still be added as a dependency.
```
yarn add https://github.com/material-foundation/material-color-utilities.git
```
*Not entirely sure if this works with `npm install`

Should be a 2 min fix.

**Files using**
`intFromHex` is `providers/ThemeProvider.tsx` & `utils/themePrinterUtils.ts`
`hexFromInt` is  `providers/ThemeProvider.tsx` & `utils/themePrinterUtils.ts`

Theres also the `{color}FromInt` methods.
Being used in `utils/colorUtils.ts` & `utils/themePrinterUtils.ts`

**Comment by BlueBazze** [comment]
Btw, great work on this. You have done a beautiful work on the project.
I will probably start converting my project over from react-paper.

**Comment by pc9795** [comment]
Thanks for raising the issue and for your kind words 😄  . Let me have a look 👀 . The thing was when I started working on this project `material-colour-utilities` was not available officially.

**Comment by BlueBazze** [comment]
I dont think it has been published just yet. The official repo lists typescript support as "coming soon". But i dont see any reason to why the repo cant be used until its been published. Tho there might be good reasoning behind putting it directly into this repo until its been published.

**Comment by pc9795** [comment]
I have added the library as a dependency.
